# Generated by Django 5.0.6 on 2024-07-10 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flan',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='flan',
            name='image_url',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='flan',
            name='is_private',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='flan',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
